### ISSUE TITLE
Information on collisions

### ISSUE THREAD

**Issue by TheEdoRan** [denostack/inthash#338]
Hi, thank you for this awesome library.
I wonder if this library can generate collisions. From what I've seen searching around the web, it shouldn't happen, right? Thanks!

P.S. I'm working with 63 bit integers (0-9223372036854775807).

**Comment by wan2land** [comment]
Thank you for your interest in the library and for your question.

I'd like to assure you that when using the inthash library with the command `deno run https://deno.land/x/inthash/cli.ts -b63` (or `npx inthash -b63`) for generating hash settings, the library is designed to avoid collisions. This command specifically generates sufficiently large prime numbers for 63-bit hashing, which is key to ensuring collision resistance, especially within the 63-bit range you mentioned.
